name: 'telegram_client_linux'
description: 'Telegram Client Lightweight, blazing and Highly customizable for make application telegram based tdlib, mtproto, or bot api and support server side.'
version: '1.8.38'
homepage: 'https://github.com/azkadev/telegram_client'
repository: 'https://github.com/azkadev/telegram_client.git'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://github.com/azkadev/telegram_client/tree/main/docs'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
false_secrets:
  - 'linux/tdlib/'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: 'flutter'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
  general_lib: '^0.0.53'
flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
topics:
  - 'telegram'
  - 'tdlib'
  - 'mtproto'
  - 'userbot'
  - 'bot'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
