name: "telegram_universe"
description: "telegram_universe is program for help you, booster up your projects significants with amazing features and super easy for use"
version: "0.0.3"
homepage: "https://youtube.com/@azkadev"
repository: "https://github.com/azkadev/telegram_client"
issue_tracker: "https://github.com/azkadev/telegram_client/issues"
documentation: "https://github.com/azkadev/telegram_client"
funding:
  - "https://github.com/sponsors/azkadev"
  - "https://www.patreon.com/c/azkadev"
  - "https://opencollective.com/azkadev"
  - "https://paypal.me/azkaaxeliongibran"
  - "https://paypal.me/azkadev"
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  ffi: "^2.1.4"
dev_dependencies:
  lints: "^5.0.0"
  test: "any"
