name: 'telegram_client_project'
description: 'Telegram Client Lightweight, blazing and Highly customizable for make application telegram based tdlib, mtproto, or bot api and support server side.'
version: '0.8.24'
homepage: 'https://github.com/azkadev/telegram_client'
repository: 'https://github.com/azkadev/telegram_client.git'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://github.com/azkadev/telegram_client/tree/main/docs'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'telegram'
  - 'tdlib'
  - 'mtproto'
  - 'userbot'
  - 'bot'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.52'
  http: '^1.2.2'
  mason_logger: '^0.3.1'
  packagex: '^0.0.67'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.2'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
