// ignore_for_file: non_constant_identifier_names
/// TelegramClientUncompleDocumentation
List<Map<String, dynamic>> telegram_client_schemes = () {
  return <Map<String, dynamic>>[
    {
      "@type": "telegramClientLibraryTdlibOptionParameter",
      "api_id": 0,
      "api_hash": "",
      "database_directory": "tg_db",
      "files_directory": "tg_file",
      "use_file_database": true,
      "use_chat_info_database": true,
      "use_message_database": true,
      "use_secret_chats": true,
      "enable_storage_optimizer": true,
      "system_language_code": "en",
      "new_verbosity_level": 0,
      "application_version": "v1",
      "device_model": "Telegram Client",
      "system_version":
          "Linux 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024",
      "database_key": "",
      "start": true,
      "database_encryption_key": "",
      "use_test_dc": false,
    },
    {
      "@type": "telegramClientLibraryError",
      "code": 500,
      "message": "",
      "description": "",
      "@extra": "",
    },
    {
      "@type": "telegramClientLibraryOk",
      "@extra": "",
    },
    {
      "@type": "telegramClientLibraryTelegramLoginWidgetUser",
      "id": "0",
      "first_name": "",
      "username": "",
      "hash": "",
      "@extra": "",
    },
    {
      "@type": "telegramClientLibraryClientData",
      "id": 0,
      "created_at": "2022-12-26T05:26:40.500935+00:00",
      "client_tg_user_id": 0,
      "client_title": "",
      "client_token": "",
      "owner_user_id": 0,
      "client_type": "",
      "from_bot_type": null,
      "can_join_groups": false,
      "can_read_all_group_messages": false,
      "from_bot_user_id": 0,
      "expire_date": 0,
      "client_username": "",
      "version": "",
      "client_id": 0,
      "client_data": "{}",
    },
  ];
}();
